time: 5  # Time
email: "example@email.com"  # Your email

send_discord: true  # Send to Discord, Email, Terminal or Notification
send_notification: true  # Send to Discord, Email, Terminal or Notification

discord_token: "TOKEN"
err: false  # err
